10 CALL CLEAR
20 DISPLAY AT(1,3):"TI SPEECH VOCAB SWEEP"
30 DISPLAY AT(3,1):"PRESS ANY KEY TO STOP"
40 N=358
50 FOR I=1 TO N
60 READ W$
65 CALL HCHAR(12,1,32,32)
70 DISPLAY AT(12,1):I;": ";W$
80 CALL SAY(W$)
90 CALL KEY(0,K,S)
100 IF S>0 THEN 130
110 NEXT I
120 GOTO 140
130 DISPLAY AT(14,1):"STOPPED AT ";I
140 DISPLAY AT(20,1):"DONE"
150 END
200 DATA "0","1","2","3","4","5","6"
210 DATA "7","8","9","A","A1","ABOUT","AFTER"
220 DATA "AGAIN","ALL","AM","AN","AND","ANSWER","ANY"
230 DATA "ARE","AS","ASSUME","AT","B","BACK","BASE"
240 DATA "BE","BETWEEN","BLACK","BLUE","BOTH","BOTTOM","BUT"
250 DATA "BUY","BY","BYE","C","CAN","CASSETTE","CENTER"
260 DATA "CHECK","CHOICE","CLEAR","COLOR","COME","COMES","COMMA"
270 DATA "COMMAND","COMPLETE","COMPLETED","COMPUTER","CONNECTED","CONSOLE","CORRECT"
280 DATA "COURSE","CYAN","D","DATA","DECIDE","DEVICE","DID"
290 DATA "DIFFERENT","DISKETTE","DO","DOES","DOING","DONE","DOUBLE"
300 DATA "DOWN","DRAW","DRAWING","E","EACH","EIGHT","EIGHTY"
310 DATA "ELEVEN","ELSE","END","ENDS","ENTER","ERROR","EXACTLY"
320 DATA "EYE","F","FIFTEEN","FIFTY","FIGURE","FIND","FINE"
330 DATA "FINISH","FINISHED","FIRST","FIT","FIVE","FOR","FORTY"
340 DATA "FOUR","FOURTEEN","FOURTH","FROM","FRONT","G","GAMES"
350 DATA "GET","GETTING","GIVE","GIVES","GO","GOES","GOING"
360 DATA "GOOD","GOODBYE","GOT","GRAY","GREEN","GUESS","H"
370 DATA "HAD","HAND","HAS","HAVE","HEAD","HEAR","HELLO"
380 DATA "HELP","HERE","HIGHER","HIT","HOME","HOW","HUNDRED"
390 DATA "HURRY","I","IF","IN","INCH","INCHES","INSTRUCTION"
400 DATA "INSTRUCTIONS","IS","IT","J","JOYSTICK","JUST","K"
410 DATA "KEY","KEYBOARD","KNOW","L","LARGE","LARGER","LARGEST"
420 DATA "LAST","LEARN","LEFT","LESS","LET","LIKE","LIKES"
430 DATA "LINE","LOAD","LONG","LOOK","LOOKS","LOWER","M"
440 DATA "MADE","MAGENTA","MAKE","ME","MEAN","MEMORY","MESSAGE"
450 DATA "MESSAGES","MIDDLE","MIGHT","MODULE","MORE","MOST","MOVE"
460 DATA "MUST","N","NAME","NEAR","NEED","NEGATIVE","NEXT"
470 DATA "NINE","NINETY","NO","NOT","NOW","NUMBER","O"
480 DATA "OF","OFF","OH","ON","ONE","ONLY","OR"
490 DATA "ORDER","OTHER","OUT","OVER","P","PART","PARTNER"
500 DATA "PARTS","PERIOD","PLAY","PLAYS","PLEASE","POINT","POSITION"
510 DATA "POSITIVE","PRESS","PRINT","PRINTER","PROBLEM","PROBLEMS","PROGRAM"
520 DATA "PUT","PUTTING","Q","R","RANDOMLY","READ","READ1"
530 DATA "RECORDER","RED","REFER","REMEMBER","RETURN","REWIND","RIGHT"
540 DATA "ROUND","S","SAID","SAVE","SAY","SAYS","SCREEN"
550 DATA "SECOND","SEE","SEES","SET","SEVEN","SEVENTY","SHAPE"
560 DATA "SHAPES","SHIFT","SHORT","SHORTER","SHOULD","SIDE","SIDES"
570 DATA "SIX","SIXTY","SMALL","SMALLER","SMALLEST","SO","SOME"
580 DATA "SORRY","SPACE","SPACES","SPELL","SQUARE","START","STEP"
590 DATA "STOP","SUM","SUPPOSED","SURE","T","TAKE","TEEN"
600 DATA "TELL","TEN","THAN","THAT","THE","THE1","THEIR"
610 DATA "THEN","THERE","THESE","THEY","THING","THINGS","THINK"
620 DATA "THIRD","THIRTEEN","THIRTY","THIS","THREE","THREW","THROUGH"
630 DATA "TIME","TO","TOGETHER","TONE","TOO","TOP","TRY"
640 DATA "TURN","TWELVE","TWENTY","TWO","TYPE","U","UHOH"
650 DATA "UNDER","UNDERSTAND","UNTIL","UP","UPPER","USE","V"
660 DATA "VARY","VERY","W","WAIT","WANT","WANTS","WAY"
670 DATA "WE","WEIGH","WEIGHT","WELL","WERE","WHAT","WHEN"
680 DATA "WHERE","WHICH","WHITE","WHO","WHY","WILL","WITH"
690 DATA "WON","WORD","WORDS","WORK","WORKING","WRITE","X"
700 DATA "Y","YELLOW","YES","YET","YOU","YOUR","Z"
710 DATA "ZERO"
