5 CALL CLEAR
10 DEF FNSQ(X)=X*X
20 DEF FNCUBE(X)=X*X*X
30 DEF FNHELLO$(N$)="HELLO, "&N$&"!"
40 PRINT "FNSQ(5)=";FNSQ(5)
50 PRINT "FNCUBE(3)=";FNCUBE(3)
60 PRINT "FNHELLO$(""WORLD"")=";FNHELLO$("WORLD")
70 END
